sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
install: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c17461eb5b3d00b3656d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
script:
- mvn clean install -DdryRun=true
