package org.dominokit.ui.tools.processor.theming;

import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import freemarker.template.TemplateExceptionHandler;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SpacingGenerator {
    public static void main(String[] args) throws IOException, TemplateException {

        List<Spacing> spacings = Arrays.asList(
                Spacing.of("0", "0"),
                Spacing.of("px", "1px"),
                Spacing.of("2px", "2px"),
                Spacing.of("4px", "4px"),
                Spacing.of("8px", "8px"),
                Spacing.of("0_5", "0.125rem"),
                Spacing.of("1", "0.25rem"),
                Spacing.of("1_5", "0.375rem"),
                Spacing.of("2", "0.5rem"),
                Spacing.of("2_5", "0.625rem"),
                Spacing.of("3", "0.75rem"),
                Spacing.of("3_5", "0.875rem"),
                Spacing.of("4", "1rem"),
                Spacing.of("5", "1.25rem"),
                Spacing.of("6", "1.5rem"),
                Spacing.of("7", "1.75rem"),
                Spacing.of("8", "2re"),
                Spacing.of("9", "2.25rem"),
                Spacing.of("10", "2.5rem"),
                Spacing.of("11", "2.75rem"),
                Spacing.of("12", "3rem"),
                Spacing.of("14", "3.5rem"),
                Spacing.of("16", "4rem"),
                Spacing.of("20", "5rem"),
                Spacing.of("24", "6rem"),
                Spacing.of("28", "7rem"),
                Spacing.of("32", "8rem"),
                Spacing.of("36", "9rem"),
                Spacing.of("40", "10rem"),
                Spacing.of("44", "11rem"),
                Spacing.of("48", "12rem"),
                Spacing.of("52", "13rem"),
                Spacing.of("56", "14rem"),
                Spacing.of("60", "15rem"),
                Spacing.of("64", "16rem"),
                Spacing.of("72", "18rem"),
                Spacing.of("80", "20rem"),
                Spacing.of("96", "24rem"),
                Spacing.of("1_2p", "50%"),
                Spacing.of("1_3p", "33.333333%"),
                Spacing.of("2_3p", "66.666667%"),
                Spacing.of("1_4p", "25%"),
                Spacing.of("3_4p", "75%"),
                Spacing.of("full", "100%")
        );

        List<SimpleCss> displayStyles = Arrays.asList(
                SimpleCss.of("block", "display: block;"),
                SimpleCss.of("inline-block", "display: inline-block;"),
                SimpleCss.of("inline", "display: inline;"),
                SimpleCss.of("flex", "display: flex;"),
                SimpleCss.of("inline-flex", "display: inline-flex;"),
                SimpleCss.of("table", "display: table;"),
                SimpleCss.of("inline-table", "display: inline-table;"),
                SimpleCss.of("table-caption", "display: table-caption;"),
                SimpleCss.of("table-cell", "display: table-cell;"),
                SimpleCss.of("table-column", "display: table-column;"),
                SimpleCss.of("table-column-group", "display: table-column-group;"),
                SimpleCss.of("table-footer-group", "display: table-footer-group;"),
                SimpleCss.of("table-header-group", "display: table-header-group;"),
                SimpleCss.of("table-row-group", "display: table-row-group;"),
                SimpleCss.of("table-row", "display: table-row;"),
                SimpleCss.of("flow-root", "display: flow-root;"),
                SimpleCss.of("grid", "display: grid;"),
                SimpleCss.of("inline-grid", "display: inline-grid;"),
                SimpleCss.of("contents", "display: contents;"),
                SimpleCss.of("list-item", "display: list-item;"),
                SimpleCss.of("hidden", "display: none;"),

                SimpleCss.of("float-right", "float: right;"),
                SimpleCss.of("float-left", "float: left;"),
                SimpleCss.of("float-none", "float: none;"),

                SimpleCss.of("clear-left", "clear: left;"),
                SimpleCss.of("clear-right", "clear: right;"),
                SimpleCss.of("clear-both", "clear: both;"),
                SimpleCss.of("clear-none", "clear: none;"),

                SimpleCss.of("isolate", "isolation: isolate;"),
                SimpleCss.of("isolation-auto", "isolation: auto;"),

                SimpleCss.of("object-contain", "object-fit: contain;"),
                SimpleCss.of("object-cover", "object-fit: cover;"),
                SimpleCss.of("object-fill", "object-fit: fill;"),
                SimpleCss.of("object-none", "object-fit: none;"),
                SimpleCss.of("object-scale-down", "object-fit: scale-down;"),

                SimpleCss.of("object-bottom", "object-position: bottom;"),
                SimpleCss.of("object-center", "object-position: center;"),
                SimpleCss.of("object-left", "object-position: left;"),
                SimpleCss.of("object-bottom", "object-position: left bottom;"),
                SimpleCss.of("object-top", "object-position: left top;"),
                SimpleCss.of("object-right", "object-position: right;"),
                SimpleCss.of("object-bottom", "object-position: right bottom;"),
                SimpleCss.of("object-top", "object-position: right top;"),
                SimpleCss.of("object-top", "object-position: top;"),


                SimpleCss.of("overflow-auto", "overflow: auto;"),
                SimpleCss.of("overflow-hidden", "overflow: hidden;"),
                SimpleCss.of("overflow-clip", "overflow: clip;"),
                SimpleCss.of("overflow-visible", "overflow: visible;"),
                SimpleCss.of("overflow-scroll", "overflow: scroll;"),
                SimpleCss.of("overflow-x-auto", "overflow-x: auto;"),
                SimpleCss.of("overflow-y-auto", "overflow-y: auto;"),
                SimpleCss.of("overflow-x-hidden", "overflow-x: hidden;"),
                SimpleCss.of("overflow-y-hidden", "overflow-y: hidden;"),
                SimpleCss.of("overflow-x-clip", "overflow-x: clip;"),
                SimpleCss.of("overflow-y-clip", "overflow-y: clip;"),
                SimpleCss.of("overflow-x-visible", "overflow-x: visible;"),
                SimpleCss.of("overflow-y-visible", "overflow-y: visible;"),
                SimpleCss.of("overflow-x-scroll", "overflow-x: scroll;"),
                SimpleCss.of("overflow-y-scroll", "overflow-y: scroll;"),


                SimpleCss.of("overscroll-auto", "overscroll-behavior: auto;"),
                SimpleCss.of("overscroll-contain", "overscroll-behavior: contain;"),
                SimpleCss.of("overscroll-none", "overscroll-behavior: none;"),
                SimpleCss.of("overscroll-y-auto", "overscroll-behavior-y: auto;"),
                SimpleCss.of("overscroll-y-contain", "overscroll-behavior-y: contain;"),
                SimpleCss.of("overscroll-y-none", "overscroll-behavior-y: none;"),
                SimpleCss.of("overscroll-x-auto", "overscroll-behavior-x: auto;"),
                SimpleCss.of("overscroll-x-contain", "overscroll-behavior-x: contain;"),
                SimpleCss.of("overscroll-x-none", "overscroll-behavior-x: none;"),


                SimpleCss.of("static", "position: static;"),
                SimpleCss.of("fixed", "position: fixed;"),
                SimpleCss.of("absolute", "position: absolute;"),
                SimpleCss.of("relative", "position: relative;"),
                SimpleCss.of("sticky", "position: sticky;"),

                SimpleCss.of("inset-0", "top: var(--dui-spc-0);\n\tright: var(--dui-spc-0);\n\tbottom: var(--dui-spc-0);\n\tleft: var(--dui-spc-0);"),
                SimpleCss.of("inset-x-0", "left: var(--dui-spc-0);\n\tright: var(--dui-spc-0);"),
                SimpleCss.of("inset-y-0", "top: var(--dui-spc-0);\n\tbottom: var(--dui-spc-0);"),
                SimpleCss.of("top-0", "top: var(--dui-spc-0);"),
                SimpleCss.of("right-0", "right: var(--dui-spc-0);"),
                SimpleCss.of("bottom-0", "bottom: var(--dui-spc-0);"),
                SimpleCss.of("left-0", "left: var(--dui-spc-0);"),
                SimpleCss.of("inset-px", "top: var(--dui-spc-px);\n\tright: var(--dui-spc-px);\n\tbottom: var(--dui-spc-px);\n\tleft: var(--dui-spc-px);"),
                SimpleCss.of("inset-x-px", "left: var(--dui-spc-px);\n\tright: var(--dui-spc-px);"),
                SimpleCss.of("inset-y-px", "top: var(--dui-spc-px);\n\tbottom: var(--dui-spc-px);"),
                SimpleCss.of("top-px", "top: var(--dui-spc-px);"),
                SimpleCss.of("right-px", "right: var(--dui-spc-px);"),
                SimpleCss.of("bottom-px", "bottom: var(--dui-spc-px);"),
                SimpleCss.of("left-px", "left: var(--dui-spc-px);"),
                SimpleCss.of("inset-0\\.5", "top: var(--dui-spc-0_5);\n\tright: var(--dui-spc-0_5);\n\tbottom: var(--dui-spc-0_5);\n\tleft: var(--dui-spc-0_5);"),
                SimpleCss.of("inset-x-0\\.5", "left: var(--dui-spc-0_5);\n\tright: var(--dui-spc-0_5);"),
                SimpleCss.of("inset-y-0\\.5", "top: var(--dui-spc-0_5);\n\tbottom: var(--dui-spc-0_5);"),
                SimpleCss.of("top-0\\.5", "top: var(--dui-spc-0_5);"),
                SimpleCss.of("right-0\\.5", "right: var(--dui-spc-0_5);"),
                SimpleCss.of("bottom-0\\.5", "bottom: var(--dui-spc-0_5);"),
                SimpleCss.of("left-0\\.5", "left: var(--dui-spc-0_5);"),
                SimpleCss.of("inset-1", "top: var(--dui-spc-1);\n\tright: var(--dui-spc-1);\n\tbottom: var(--dui-spc-1);\n\tleft: var(--dui-spc-1);"),
                SimpleCss.of("inset-x-1", "left: var(--dui-spc-1);\n\tright: var(--dui-spc-1);"),
                SimpleCss.of("inset-y-1", "top: var(--dui-spc-1);\n\tbottom: var(--dui-spc-1);"),
                SimpleCss.of("top-1", "top: var(--dui-spc-1);"),
                SimpleCss.of("right-1", "right: var(--dui-spc-1);"),
                SimpleCss.of("bottom-1", "bottom: var(--dui-spc-1);"),
                SimpleCss.of("left-1", "left: var(--dui-spc-1);"),
                SimpleCss.of("inset-1\\.5", "top: var(--dui-spc-1_5);\n\tright: var(--dui-spc-1_5);\n\tbottom: var(--dui-spc-1_5);\n\tleft: var(--dui-spc-1_5);"),
                SimpleCss.of("inset-x-1\\.5", "left: var(--dui-spc-1_5);\n\tright: var(--dui-spc-1_5);"),
                SimpleCss.of("inset-y-1\\.5", "top: var(--dui-spc-1_5);\n\tbottom: var(--dui-spc-1_5);"),
                SimpleCss.of("top-1\\.5", "top: var(--dui-spc-1_5);"),
                SimpleCss.of("right-1\\.5", "right: var(--dui-spc-1_5);"),
                SimpleCss.of("bottom-1\\.5", "bottom: var(--dui-spc-1_5);"),
                SimpleCss.of("left-1\\.5", "left: var(--dui-spc-1_5);"),
                SimpleCss.of("inset-2", "top: var(--dui-spc-2);\n\tright: var(--dui-spc-2);\n\tbottom: var(--dui-spc-2);\n\tleft: var(--dui-spc-2);"),
                SimpleCss.of("inset-x-2", "left: var(--dui-spc-2);\n\tright: var(--dui-spc-2);"),
                SimpleCss.of("inset-y-2", "top: var(--dui-spc-2);\n\tbottom: var(--dui-spc-2);"),
                SimpleCss.of("top-2", "top: var(--dui-spc-2);"),
                SimpleCss.of("right-2", "right: var(--dui-spc-2);"),
                SimpleCss.of("bottom-2", "bottom: var(--dui-spc-2);"),
                SimpleCss.of("left-2", "left: var(--dui-spc-2);"),
                SimpleCss.of("inset-2\\.5", "top: var(--dui-spc-2_5);\n\tright: var(--dui-spc-2_5);\n\tbottom: var(--dui-spc-2_5);\n\tleft: var(--dui-spc-2_5);"),
                SimpleCss.of("inset-x-2\\.5", "left: var(--dui-spc-2_5);\n\tright: var(--dui-spc-2_5);"),
                SimpleCss.of("inset-y-2\\.5", "top: var(--dui-spc-2_5);\n\tbottom: var(--dui-spc-2_5);"),
                SimpleCss.of("top-2\\.5", "top: var(--dui-spc-2_5);"),
                SimpleCss.of("right-2\\.5", "right: var(--dui-spc-2_5);"),
                SimpleCss.of("bottom-2\\.5", "bottom: var(--dui-spc-2_5);"),
                SimpleCss.of("left-2\\.5", "left: var(--dui-spc-2_5);"),
                SimpleCss.of("inset-3", "top: var(--dui-spc-3);\n\tright: var(--dui-spc-3);\n\tbottom: var(--dui-spc-3);\n\tleft: var(--dui-spc-3);"),
                SimpleCss.of("inset-x-3", "left: var(--dui-spc-3);\n\tright: var(--dui-spc-3);"),
                SimpleCss.of("inset-y-3", "top: var(--dui-spc-3);\n\tbottom: var(--dui-spc-3);"),
                SimpleCss.of("top-3", "top: var(--dui-spc-3);"),
                SimpleCss.of("right-3", "right: var(--dui-spc-3);"),
                SimpleCss.of("bottom-3", "bottom: var(--dui-spc-3);"),
                SimpleCss.of("left-3", "left: var(--dui-spc-3);"),
                SimpleCss.of("inset-3\\.5", "top: var(--dui-spc-3_5);\n\tright: var(--dui-spc-3_5);\n\t bottom: var(--dui-spc-3_5);\n\tleft: var(--dui-spc-3_5);"),
                SimpleCss.of("inset-x-3\\.5", "left: var(--dui-spc-3_5);\n\tright: var(--dui-spc-3_5);"),
                SimpleCss.of("inset-y-3\\.5", "top: var(--dui-spc-3_5);bottom: var(--dui-spc-3_5);"),
                SimpleCss.of("top-3\\.5", "top: var(--dui-spc-3_5);"),
                SimpleCss.of("right-3\\.5", "right: var(--dui-spc-3_5);"),
                SimpleCss.of("bottom-3\\.5", "bottom: var(--dui-spc-3_5);"),
                SimpleCss.of("left-3\\.5", "left: var(--dui-spc-3_5);"),
                SimpleCss.of("inset-4", "top: var(--dui-spc-4);\n\tright: var(--dui-spc-4);\n\tbottom: var(--dui-spc-4);\n\tleft: var(--dui-spc-4);"),
                SimpleCss.of("inset-x-4", "left: var(--dui-spc-4);\n\tright: var(--dui-spc-4);"),
                SimpleCss.of("inset-y-4", "top: var(--dui-spc-4);\n\tbottom: var(--dui-spc-4);"),
                SimpleCss.of("top-4", "top: var(--dui-spc-4);"),
                SimpleCss.of("right-4", "right: var(--dui-spc-4);"),
                SimpleCss.of("bottom-4", "bottom: var(--dui-spc-4);"),
                SimpleCss.of("left-4", "left: var(--dui-spc-4);"),
                SimpleCss.of("inset-5", "top: var(--dui-spc-5);\n\tright: var(--dui-spc-5);\n\tbottom: var(--dui-spc-5);\n\tleft: var(--dui-spc-5);"),
                SimpleCss.of("inset-x-5", "left: var(--dui-spc-5);\n\tright: var(--dui-spc-5);"),
                SimpleCss.of("inset-y-5", "top: var(--dui-spc-5);\n\tbottom: var(--dui-spc-5);"),
                SimpleCss.of("top-5", "top: var(--dui-spc-5);"),
                SimpleCss.of("right-5", "right: var(--dui-spc-5);"),
                SimpleCss.of("bottom-5", "bottom: var(--dui-spc-5);"),
                SimpleCss.of("left-5", "left: var(--dui-spc-5);"),
                SimpleCss.of("inset-6", "top: var(--dui-spc-6);\n\tright: var(--dui-spc-6);\n\tbottom: var(--dui-spc-6);\n\tleft: var(--dui-spc-6);"),
                SimpleCss.of("inset-x-6", "left: var(--dui-spc-6);\n\tright: var(--dui-spc-6);"),
                SimpleCss.of("inset-y-6", "top: var(--dui-spc-6);\n\tbottom: var(--dui-spc-6);"),
                SimpleCss.of("top-6", "top: var(--dui-spc-6);"),
                SimpleCss.of("right-6", "right: var(--dui-spc-6);"),
                SimpleCss.of("bottom-6", "bottom: var(--dui-spc-6);"),
                SimpleCss.of("left-6", "left: var(--dui-spc-6);"),
                SimpleCss.of("inset-7", "top: var(--dui-spc-7);\n\tright: var(--dui-spc-7);\n\tbottom: var(--dui-spc-7);\n\tleft: var(--dui-spc-7);"),
                SimpleCss.of("inset-x-7", "left: var(--dui-spc-7);\n\tright: var(--dui-spc-7);"),
                SimpleCss.of("inset-y-7", "top: var(--dui-spc-7);\n\tbottom: var(--dui-spc-7);"),
                SimpleCss.of("top-7", "top: var(--dui-spc-7);"),
                SimpleCss.of("right-7", "right: var(--dui-spc-7);"),
                SimpleCss.of("bottom-7", "bottom: var(--dui-spc-7);"),
                SimpleCss.of("left-7", "left: var(--dui-spc-7);"),
                SimpleCss.of("inset-8", "top: var(--dui-spc-8);\n\tright: var(--dui-spc-8);\n\tbottom: var(--dui-spc-8);\n\tleft: var(--dui-spc-8);"),
                SimpleCss.of("inset-x-8", "left: var(--dui-spc-8);\n\tright: var(--dui-spc-8);"),
                SimpleCss.of("inset-y-8", "top: var(--dui-spc-8);\n\tbottom: var(--dui-spc-8);"),
                SimpleCss.of("top-8", "top: var(--dui-spc-8);"),
                SimpleCss.of("right-8", "right: var(--dui-spc-8);"),
                SimpleCss.of("bottom-8", "bottom: var(--dui-spc-8);"),
                SimpleCss.of("left-8", "left: var(--dui-spc-8);"),
                SimpleCss.of("inset-9", "top: var(--dui-spc-9);\n\tright: var(--dui-spc-9);\n\tbottom: var(--dui-spc-9);\n\tleft: var(--dui-spc-9);"),
                SimpleCss.of("inset-x-9", "left: var(--dui-spc-9);\n\tright: var(--dui-spc-9);"),
                SimpleCss.of("inset-y-9", "top: var(--dui-spc-9);\n\tbottom: var(--dui-spc-9);"),
                SimpleCss.of("top-9", "top: var(--dui-spc-9);"),
                SimpleCss.of("right-9", "right: var(--dui-spc-9);"),
                SimpleCss.of("bottom-9", "bottom: var(--dui-spc-9);"),
                SimpleCss.of("left-9", "left: var(--dui-spc-9);"),
                SimpleCss.of("inset-10", "top: var(--dui-spc-10);\n\tright: var(--dui-spc-10);\n\tbottom: var(--dui-spc-10);\n\tleft: var(--dui-spc-10);"),
                SimpleCss.of("inset-x-10", "left: var(--dui-spc-10);\n\tright: var(--dui-spc-10);"),
                SimpleCss.of("inset-y-10", "top: var(--dui-spc-10);\n\tbottom: var(--dui-spc-10);"),
                SimpleCss.of("top-10", "top: var(--dui-spc-10);"),
                SimpleCss.of("right-10", "right: var(--dui-spc-10);"),
                SimpleCss.of("bottom-10", "bottom: var(--dui-spc-10);"),
                SimpleCss.of("left-10", "left: var(--dui-spc-10);"),
                SimpleCss.of("inset-11", "top: var(--dui-spc-11);\n\tright: var(--dui-spc-11);\n\tbottom: var(--dui-spc-11);\n\tleft: var(--dui-spc-11);"),
                SimpleCss.of("inset-x-11", "left: var(--dui-spc-11);\n\tright: var(--dui-spc-11);"),
                SimpleCss.of("inset-y-11", "top: var(--dui-spc-11);\n\tbottom: var(--dui-spc-11);"),
                SimpleCss.of("top-11", "top: var(--dui-spc-11);"),
                SimpleCss.of("right-11", "right: var(--dui-spc-11);"),
                SimpleCss.of("bottom-11", "bottom: var(--dui-spc-11);"),
                SimpleCss.of("left-11", "left: var(--dui-spc-11);"),
                SimpleCss.of("inset-12", "top: var(--dui-spc-12);\n\tright: var(--dui-spc-12);\n\tbottom: var(--dui-spc-12);\n\tleft: var(--dui-spc-12);"),
                SimpleCss.of("inset-x-12", "left: var(--dui-spc-12);\n\tright: var(--dui-spc-12);"),
                SimpleCss.of("inset-y-12", "top: var(--dui-spc-12);\n\tbottom: var(--dui-spc-12);"),
                SimpleCss.of("top-12", "top: var(--dui-spc-12);"),
                SimpleCss.of("right-12", "right: var(--dui-spc-12);"),
                SimpleCss.of("bottom-12", "bottom: var(--dui-spc-12);"),
                SimpleCss.of("left-12", "left: var(--dui-spc-12);"),
                SimpleCss.of("inset-14", "top: var(--dui-spc-14);\n\tright: var(--dui-spc-14);\n\tbottom: var(--dui-spc-14);\n\tleft: var(--dui-spc-14);"),
                SimpleCss.of("inset-x-14", "left: var(--dui-spc-14);\n\tright: var(--dui-spc-14);"),
                SimpleCss.of("inset-y-14", "top: var(--dui-spc-14);\n\tbottom: var(--dui-spc-14);"),
                SimpleCss.of("top-14", "top: var(--dui-spc-14);"),
                SimpleCss.of("right-14", "right: var(--dui-spc-14);"),
                SimpleCss.of("bottom-14", "bottom: var(--dui-spc-14);"),
                SimpleCss.of("left-14", "left: var(--dui-spc-14);"),
                SimpleCss.of("inset-16", "top: var(--dui-spc-16);\n\tright: var(--dui-spc-16);\n\tbottom: var(--dui-spc-16);\n\tleft: var(--dui-spc-16);"),
                SimpleCss.of("inset-x-16", "left: var(--dui-spc-16);\n\tright: var(--dui-spc-16);"),
                SimpleCss.of("inset-y-16", "top: var(--dui-spc-16);\n\tbottom: var(--dui-spc-16);"),
                SimpleCss.of("top-16", "top: var(--dui-spc-16);"),
                SimpleCss.of("right-16", "right: var(--dui-spc-16);"),
                SimpleCss.of("bottom-16", "bottom: var(--dui-spc-16);"),
                SimpleCss.of("left-16", "left: var(--dui-spc-16);"),
                SimpleCss.of("inset-20", "top: var(--dui-spc-20);\n\tright: var(--dui-spc-20);\n\tbottom: var(--dui-spc-20);\n\tleft: var(--dui-spc-20);"),
                SimpleCss.of("inset-x-20", "left: var(--dui-spc-20);\n\tright: var(--dui-spc-20);"),
                SimpleCss.of("inset-y-20", "top: var(--dui-spc-20);\n\tbottom: var(--dui-spc-20);"),
                SimpleCss.of("top-20", "top: var(--dui-spc-20);"),
                SimpleCss.of("right-20", "right: var(--dui-spc-20);"),
                SimpleCss.of("bottom-20", "bottom: var(--dui-spc-20);"),
                SimpleCss.of("left-20", "left: var(--dui-spc-20);"),
                SimpleCss.of("inset-24", "top: var(--dui-spc-24);\n\tright: var(--dui-spc-24);\n\tbottom: var(--dui-spc-24);\n\tleft: var(--dui-spc-24);"),
                SimpleCss.of("inset-x-24", "left: var(--dui-spc-24);\n\tright: var(--dui-spc-24);"),
                SimpleCss.of("inset-y-24", "top: var(--dui-spc-24);\n\tbottom: var(--dui-spc-24);"),
                SimpleCss.of("top-24", "top: var(--dui-spc-24);"),
                SimpleCss.of("right-24", "right: var(--dui-spc-24);"),
                SimpleCss.of("bottom-24", "bottom: var(--dui-spc-24);"),
                SimpleCss.of("left-24", "left: var(--dui-spc-24);"),
                SimpleCss.of("inset-28", "top: var(--dui-spc-28);\n\tright: var(--dui-spc-28);\n\tbottom: var(--dui-spc-28);\n\tleft: var(--dui-spc-28);"),
                SimpleCss.of("inset-x-28", "left: var(--dui-spc-28);\n\tright: var(--dui-spc-28);"),
                SimpleCss.of("inset-y-28", "top: var(--dui-spc-28);\n\tbottom: var(--dui-spc-28);"),
                SimpleCss.of("top-28", "top: var(--dui-spc-28);"),
                SimpleCss.of("right-28", "right: var(--dui-spc-28);"),
                SimpleCss.of("bottom-28", "bottom: var(--dui-spc-28);"),
                SimpleCss.of("left-28", "left: var(--dui-spc-28);"),
                SimpleCss.of("inset-32", "top: var(--dui-spc-32);\n\tright: var(--dui-spc-32);\n\tbottom: var(--dui-spc-32);\n\tleft: var(--dui-spc-32);"),
                SimpleCss.of("inset-x-32", "left: var(--dui-spc-32);\n\tright: var(--dui-spc-32);"),
                SimpleCss.of("inset-y-32", "top: var(--dui-spc-32);\n\tbottom: var(--dui-spc-32);"),
                SimpleCss.of("top-32", "top: var(--dui-spc-32);"),
                SimpleCss.of("right-32", "right: var(--dui-spc-32);"),
                SimpleCss.of("bottom-32", "bottom: var(--dui-spc-32);"),
                SimpleCss.of("left-32", "left: var(--dui-spc-32);"),
                SimpleCss.of("inset-36", "top: var(--dui-spc-36);\n\tright: var(--dui-spc-36);\n\tbottom: var(--dui-spc-36);\n\tleft: var(--dui-spc-36);"),
                SimpleCss.of("inset-x-36", "left: var(--dui-spc-36);\n\tright: var(--dui-spc-36);"),
                SimpleCss.of("inset-y-36", "top: var(--dui-spc-36);\n\tbottom: var(--dui-spc-36);"),
                SimpleCss.of("top-36", "top: var(--dui-spc-36);"),
                SimpleCss.of("right-36", "right: var(--dui-spc-36);"),
                SimpleCss.of("bottom-36", "bottom: var(--dui-spc-36);"),
                SimpleCss.of("left-36", "left: var(--dui-spc-36);"),
                SimpleCss.of("inset-40", "top: var(--dui-spc-40);\n\tright: var(--dui-spc-40);\n\tbottom: var(--dui-spc-40);\n\tleft: var(--dui-spc-40);"),
                SimpleCss.of("inset-x-40", "left: var(--dui-spc-40);\n\tright: var(--dui-spc-40);"),
                SimpleCss.of("inset-y-40", "top: var(--dui-spc-40);\n\tbottom: var(--dui-spc-40);"),
                SimpleCss.of("top-40", "top: var(--dui-spc-40);"),
                SimpleCss.of("right-40", "right: var(--dui-spc-40);"),
                SimpleCss.of("bottom-40", "bottom: var(--dui-spc-40);"),
                SimpleCss.of("left-40", "left: var(--dui-spc-40);"),


                SimpleCss.of("inset-44", "top: var(--dui-spc-44);\n\tright: var(--dui-spc-44);\n\tbottom: var(--dui-spc-44);\n\tleft: var(--dui-spc-44);"),
                SimpleCss.of("inset-x-44", "left: var(--dui-spc-44);\n\tright: var(--dui-spc-44);"),
                SimpleCss.of("inset-y-44", "top: var(--dui-spc-44);bottom: var(--dui-spc-44);"),
                SimpleCss.of("top-44", "top: var(--dui-spc-44);"),
                SimpleCss.of("right-44", "right: var(--dui-spc-44);"),
                SimpleCss.of("bottom-44", "bottom: var(--dui-spc-44);"),
                SimpleCss.of("left-44", "left: var(--dui-spc-44);"),
                SimpleCss.of("inset-48", "top: var(--dui-spc-48);\n\tright: var(--dui-spc-48);\n\tbottom: var(--dui-spc-48);\n\tleft: var(--dui-spc-48);"),
                SimpleCss.of("inset-x-48", "left: var(--dui-spc-48);\n\tright: var(--dui-spc-48);"),
                SimpleCss.of("inset-y-48", "top: var(--dui-spc-48);\n\tbottom: var(--dui-spc-48);"),
                SimpleCss.of("top-48", "top: var(--dui-spc-48);"),
                SimpleCss.of("right-48", "right: var(--dui-spc-48);"),
                SimpleCss.of("bottom-48", "bottom: var(--dui-spc-48);"),
                SimpleCss.of("left-48", "left: var(--dui-spc-48);"),
                SimpleCss.of("inset-52", "top: var(--dui-spc-52);\n\tright: var(--dui-spc-52);\n\tbottom: var(--dui-spc-52);\n\tleft: var(--dui-spc-52);"),
                SimpleCss.of("inset-x-52", "left: var(--dui-spc-52);\n\tright: var(--dui-spc-52);"),
                SimpleCss.of("inset-y-52", "top: var(--dui-spc-52);\n\tbottom: var(--dui-spc-52);"),
                SimpleCss.of("top-52", "top: var(--dui-spc-52);"),
                SimpleCss.of("right-52", "right: var(--dui-spc-52);"),
                SimpleCss.of("bottom-52", "bottom: var(--dui-spc-52);"),
                SimpleCss.of("left-52", "left: var(--dui-spc-52);"),
                SimpleCss.of("inset-56", "top: var(--dui-spc-56);\n\tright: var(--dui-spc-56);\n\tbottom: var(--dui-spc-56);\n\tleft: var(--dui-spc-56);"),
                SimpleCss.of("inset-x-56", "left: var(--dui-spc-56);\n\tright: var(--dui-spc-56);"),
                SimpleCss.of("inset-y-56", "top: var(--dui-spc-56);\n\tbottom: var(--dui-spc-56);"),
                SimpleCss.of("top-56", "top: var(--dui-spc-56);"),
                SimpleCss.of("right-56", "right: var(--dui-spc-56);"),
                SimpleCss.of("bottom-56", "bottom: var(--dui-spc-56);"),
                SimpleCss.of("left-56", "left: var(--dui-spc-56);"),
                SimpleCss.of("inset-60", "top: var(--dui-spc-60);\n\tright: var(--dui-spc-60);\n\tbottom: var(--dui-spc-60);\n\tleft: var(--dui-spc-60);"),
                SimpleCss.of("inset-x-60", "left: var(--dui-spc-60);\n\tright: var(--dui-spc-60);"),
                SimpleCss.of("inset-y-60", "top: var(--dui-spc-60);\n\tbottom: var(--dui-spc-60);"),
                SimpleCss.of("top-60", "top: var(--dui-spc-60);"),
                SimpleCss.of("right-60", "right: var(--dui-spc-60);"),
                SimpleCss.of("bottom-60", "bottom: var(--dui-spc-60);"),
                SimpleCss.of("left-60", "left: var(--dui-spc-60);"),
                SimpleCss.of("inset-64", "top: var(--dui-spc-64);\n\tright: var(--dui-spc-64);\n\tbottom: var(--dui-spc-64);\n\tleft: var(--dui-spc-64);"),
                SimpleCss.of("inset-x-64", "left: var(--dui-spc-64);\n\tright: var(--dui-spc-64);"),
                SimpleCss.of("inset-y-64", "top: var(--dui-spc-64);\n\tbottom: var(--dui-spc-64);"),
                SimpleCss.of("top-64", "top: var(--dui-spc-64);"),
                SimpleCss.of("right-64", "right: var(--dui-spc-64);"),
                SimpleCss.of("bottom-64", "bottom: var(--dui-spc-64);"),
                SimpleCss.of("left-64", "left: var(--dui-spc-64);"),
                SimpleCss.of("inset-72", "top: var(--dui-spc-72);\n\tright: var(--dui-spc-72);\n\tbottom: var(--dui-spc-72);\n\tleft: var(--dui-spc-72);"),
                SimpleCss.of("inset-x-72", "left: var(--dui-spc-72);\n\tright: var(--dui-spc-72);"),
                SimpleCss.of("inset-y-72", "top: var(--dui-spc-72);\n\tbottom: var(--dui-spc-72);"),
                SimpleCss.of("top-72", "top: var(--dui-spc-72);"),
                SimpleCss.of("right-72", "right: var(--dui-spc-72);"),
                SimpleCss.of("bottom-72", "bottom: var(--dui-spc-72);"),
                SimpleCss.of("left-72", "left: var(--dui-spc-72);"),

                SimpleCss.of("inset-80", "top: var(--dui-spc-80);\n\tright: var(--dui-spc-80);\n\tbottom: var(--dui-spc-80);\n\tleft: var(--dui-spc-80);"),
                SimpleCss.of("inset-x-80", "left: var(--dui-spc-80);\n\tright: var(--dui-spc-80);"),
                SimpleCss.of("inset-y-80", "top: var(--dui-spc-80);\n\tbottom: var(--dui-spc-80);"),
                SimpleCss.of("top-80", "top: var(--dui-spc-80);"),
                SimpleCss.of("right-80", "right: var(--dui-spc-80);"),
                SimpleCss.of("bottom-80", "bottom: var(--dui-spc-80);"),
                SimpleCss.of("left-80", "left: var(--dui-spc-80);"),

                SimpleCss.of("inset-96", "top: var(--dui-spc-96);\n\tright: var(--dui-spc-96);\n\tbottom: var(--dui-spc-96);\n\tleft: var(--dui-spc-96);"),
                SimpleCss.of("inset-x-96", "left: var(--dui-spc-96);\n\tright: var(--dui-spc-96);"),
                SimpleCss.of("inset-y-96", "top: var(--dui-spc-96);\n\tbottom: var(--dui-spc-96);"),
                SimpleCss.of("top-96", "top: var(--dui-spc-96);"),
                SimpleCss.of("right-96", "right: var(--dui-spc-96);"),
                SimpleCss.of("bottom-96", "bottom: var(--dui-spc-96);"),
                SimpleCss.of("left-96", "left: var(--dui-spc-96);"),

                SimpleCss.of("inset-auto", "top: auto;\n\tright: auto;\n\tbottom: auto;\n\tleft: auto;"),
                SimpleCss.of("inset-1_2p", "top: var(--dui-spc-1_2p);\n\tright: var(--dui-spc-1_2p);\n\tbottom: var(--dui-spc-1_2p);\n\tleft: var(--dui-spc-1_2p);"),
                SimpleCss.of("inset-1_3p", "top: var(--dui-spc-1_3p);\n\tright: var(--dui-spc-1_3p);\n\tbottom: var(--dui-spc-1_3p);\n\tleft: var(--dui-spc-1_3p);"),
                SimpleCss.of("inset-2_3p", "top: var(--dui-spc-2_3p);\n\tright: var(--dui-spc-2_3p);\n\tbottom: var(--dui-spc-2_3p);\n\tleft: var(--dui-spc-2_3p);"),
                SimpleCss.of("inset-1_4p", "top: var(--dui-spc-1_4p);\n\tright: var(--dui-spc-1_4p);\n\tbottom: var(--dui-spc-1_4p);\n\tleft: var(--dui-spc-1_4p);"),
                SimpleCss.of("inset-3_4p", "top: var(--dui-spc-3_4p);\n\tright: var(--dui-spc-3_4p);\n\tbottom: var(--dui-spc-3_4p);\n\tleft: var(--dui-spc-3_4p);"),
                SimpleCss.of("inset-full", "top: var(--dui-spc-full);\n\tright: var(--dui-spc-full);\n\tbottom: var(--dui-spc-full);\n\tleft: var(--dui-spc-full);"),
                SimpleCss.of("inset-x-auto", "left: auto;\n\tright: auto;"),
                SimpleCss.of("inset-x-1_2p", "left: var(--dui-spc-1_2p);\n\tright: var(--dui-spc-1_2p);"),
                SimpleCss.of("inset-x-1_3p", "left: var(--dui-spc-1_3p);\n\tright: var(--dui-spc-1_3p);"),
                SimpleCss.of("inset-x-2_3p", "left: var(--dui-spc-2_3p);\n\tright: var(--dui-spc-2_3p);"),
                SimpleCss.of("inset-x-1_4p", "left: var(--dui-spc-1_4p);\n\tright: var(--dui-spc-1_4p);"),
                SimpleCss.of("inset-x-3_4p", "left: var(--dui-spc-3_4p);\n\tright: var(--dui-spc-3_4p);"),
                SimpleCss.of("inset-x-full", "left: var(--dui-spc-full);\n\tright: var(--dui-spc-full);"),
                SimpleCss.of("inset-y-auto", "top: auto;\n\tbottom: auto;"),
                SimpleCss.of("inset-y-1_2p", "top: var(--dui-spc-1_2p);\n\tbottom: var(--dui-spc-1_2p);"),
                SimpleCss.of("inset-y-1_3p", "top: var(--dui-spc-1_3p);\n\tbottom: var(--dui-spc-1_3p);"),
                SimpleCss.of("inset-y-2_3p", "top: var(--dui-spc-2_3p);\n\tbottom: var(--dui-spc-2_3p);"),
                SimpleCss.of("inset-y-1_4p", "top: var(--dui-spc-1_4p);\n\tbottom: var(--dui-spc-1_4p);"),
                SimpleCss.of("inset-y-3_4p", "top: var(--dui-spc-3_4p);\n\tbottom: var(--dui-spc-3_4p);"),
                SimpleCss.of("inset-y-full", "top: var(--dui-spc-full);\n\tbottom: var(--dui-spc-full);"),
                SimpleCss.of("top-auto", "top: auto;"),
                SimpleCss.of("top-1_2p", "top: var(--dui-spc-1_2p);"),
                SimpleCss.of("top-1_3p", "top: var(--dui-spc-1_3p);"),
                SimpleCss.of("top-2_3p", "top: var(--dui-spc-2_3p);"),
                SimpleCss.of("top-1_4p", "top: var(--dui-spc-1_4p);"),
                SimpleCss.of("top-3_4p", "top: var(--dui-spc-3_4p);"),
                SimpleCss.of("top-full", "top: var(--dui-spc-full);"),
                SimpleCss.of("right-auto", "right: auto;"),
                SimpleCss.of("right-1_2p", "right: var(--dui-spc-1_2p);"),
                SimpleCss.of("right-1_3p", "right: var(--dui-spc-1_3p);"),
                SimpleCss.of("right-2_3p", "right: var(--dui-spc-2_3p);"),
                SimpleCss.of("right-1_4p", "right: var(--dui-spc-1_4p);"),
                SimpleCss.of("right-3_4p", "right: var(--dui-spc-3_4p);"),
                SimpleCss.of("right-full", "right: var(--dui-spc-full);"),
                SimpleCss.of("bottom-auto", "bottom: auto;"),
                SimpleCss.of("bottom-1_2p", "bottom: var(--dui-spc-1_2p);"),
                SimpleCss.of("bottom-1_3p", "bottom: var(--dui-spc-1_3p);"),
                SimpleCss.of("bottom-2_3p", "bottom: var(--dui-spc-2_3p);"),
                SimpleCss.of("bottom-1_4p", "bottom: var(--dui-spc-1_4p);"),
                SimpleCss.of("bottom-3_4p", "bottom: var(--dui-spc-3_4p);"),
                SimpleCss.of("bottom-full", "bottom: var(--dui-spc-full);"),
                SimpleCss.of("left-auto", "left: auto;"),
                SimpleCss.of("left-1_2p", "left: var(--dui-spc-1_2p);"),
                SimpleCss.of("left-1_3p", "left: var(--dui-spc-1_3p);"),
                SimpleCss.of("left-2_3p", "left: var(--dui-spc-2_3p);"),
                SimpleCss.of("left-1_4p", "left: var(--dui-spc-1_4p);"),
                SimpleCss.of("left-3_4p", "left: var(--dui-spc-3_4p);"),
                SimpleCss.of("left-full", "left: var(--dui-spc-full);"),

                SimpleCss.of("visible", "visibility: visible;"),
                SimpleCss.of("invisible", "visibility: hidden;"),

                SimpleCss.of("z-0", "z-index: 0;"),
                SimpleCss.of("z-10", "z-index: 10;"),
                SimpleCss.of("z-20", "z-index: 20;"),
                SimpleCss.of("z-30", "z-index: 30;"),
                SimpleCss.of("z-40", "z-index: 40;"),
                SimpleCss.of("z-50", "z-index: 50;"),
                SimpleCss.of("z-auto", "z-index: auto;"),

                SimpleCss.of("flex-row", "flex-direction: row;"),
                SimpleCss.of("flex-row-reverse", "flex-direction: row-reverse;"),
                SimpleCss.of("flex-col", "flex-direction: column;"),
                SimpleCss.of("flex-col-reverse", "flex-direction: column-reverse;"),

                SimpleCss.of("flex-wrap", "flex-wrap: wrap;"),
                SimpleCss.of("flex-wrap-reverse", "flex-wrap: wrap-reverse;"),
                SimpleCss.of("flex-nowrap", "flex-wrap: nowrap;"),

                SimpleCss.of("flex-1", "flex: 1 1 0%;"),
                SimpleCss.of("flex-auto", "flex: 1 1 auto;"),
                SimpleCss.of("flex-initial", "flex: 0 1 auto;"),
                SimpleCss.of("flex-none", "flex: none;"),

                SimpleCss.of("grow", "flex-grow: 1;"),
                SimpleCss.of("grow-0", "flex-grow: 0;"),

                SimpleCss.of("shrink", "flex-shrink: 1;"),
                SimpleCss.of("shrink-0", "flex-shrink: 0;"),

                SimpleCss.of("order-1", "order: 1;"),
                SimpleCss.of("order-2", "order: 2;"),
                SimpleCss.of("order-3", "order: 3;"),
                SimpleCss.of("order-4", "order: 4;"),
                SimpleCss.of("order-5", "order: 5;"),
                SimpleCss.of("order-6", "order: 6;"),
                SimpleCss.of("order-7", "order: 7;"),
                SimpleCss.of("order-8", "order: 8;"),
                SimpleCss.of("order-9", "order: 9;"),
                SimpleCss.of("order-10", "order: 10;"),
                SimpleCss.of("order-11", "order: 11;"),
                SimpleCss.of("order-12", "order: 12;"),
                SimpleCss.of("order-first", "order: -9999;"),
                SimpleCss.of("order-last", "order: 9999;"),
                SimpleCss.of("order-none", "order: 0;"),


                SimpleCss.of("grid-cols-1", "grid-template-columns: repeat(1, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-2", "grid-template-columns: repeat(2, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-3", "grid-template-columns: repeat(3, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-4", "grid-template-columns: repeat(4, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-5", "grid-template-columns: repeat(5, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-6", "grid-template-columns: repeat(6, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-7", "grid-template-columns: repeat(7, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-8", "grid-template-columns: repeat(8, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-9", "grid-template-columns: repeat(9, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-10", "grid-template-columns: repeat(10, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-11", "grid-template-columns: repeat(11, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-12", "grid-template-columns: repeat(12, minmax(0, 1fr));"),
                SimpleCss.of("grid-cols-none", "grid-template-columns: none;"),

                SimpleCss.of("col-auto", "grid-column: auto;"),
                SimpleCss.of("col-span-1", "grid-column: span 1 / span 1;"),
                SimpleCss.of("col-span-2", "grid-column: span 2 / span 2;"),
                SimpleCss.of("col-span-3", "grid-column: span 3 / span 3;"),
                SimpleCss.of("col-span-4", "grid-column: span 4 / span 4;"),
                SimpleCss.of("col-span-5", "grid-column: span 5 / span 5;"),
                SimpleCss.of("col-span-6", "grid-column: span 6 / span 6;"),
                SimpleCss.of("col-span-7", "grid-column: span 7 / span 7;"),
                SimpleCss.of("col-span-8", "grid-column: span 8 / span 8;"),
                SimpleCss.of("col-span-9", "grid-column: span 9 / span 9;"),
                SimpleCss.of("col-span-10", "grid-column: span 10 / span 10;"),
                SimpleCss.of("col-span-11", "grid-column: span 11 / span 11;"),
                SimpleCss.of("col-span-12", "grid-column: span 12 / span 12;"),
                SimpleCss.of("col-span-full", "grid-column: 1 / -1;"),
                SimpleCss.of("col-start-1", "grid-column-start: 1;"),
                SimpleCss.of("col-start-2", "grid-column-start: 2;"),
                SimpleCss.of("col-start-3", "grid-column-start: 3;"),
                SimpleCss.of("col-start-4", "grid-column-start: 4;"),
                SimpleCss.of("col-start-5", "grid-column-start: 5;"),
                SimpleCss.of("col-start-6", "grid-column-start: 6;"),
                SimpleCss.of("col-start-7", "grid-column-start: 7;"),
                SimpleCss.of("col-start-8", "grid-column-start: 8;"),
                SimpleCss.of("col-start-9", "grid-column-start: 9;"),
                SimpleCss.of("col-start-10", "grid-column-start: 10;"),
                SimpleCss.of("col-start-11", "grid-column-start: 11;"),
                SimpleCss.of("col-start-12", "grid-column-start: 12;"),
                SimpleCss.of("col-start-13", "grid-column-start: 13;"),
                SimpleCss.of("col-start-auto", "grid-column-start: auto;"),
                SimpleCss.of("col-end-1", "grid-column-end: 1;"),
                SimpleCss.of("col-end-2", "grid-column-end: 2;"),
                SimpleCss.of("col-end-3", "grid-column-end: 3;"),
                SimpleCss.of("col-end-4", "grid-column-end: 4;"),
                SimpleCss.of("col-end-5", "grid-column-end: 5;"),
                SimpleCss.of("col-end-6", "grid-column-end: 6;"),
                SimpleCss.of("col-end-7", "grid-column-end: 7;"),
                SimpleCss.of("col-end-8", "grid-column-end: 8;"),
                SimpleCss.of("col-end-9", "grid-column-end: 9;"),
                SimpleCss.of("col-end-10", "grid-column-end: 10;"),
                SimpleCss.of("col-end-11", "grid-column-end: 11;"),
                SimpleCss.of("col-end-12", "grid-column-end: 12;"),
                SimpleCss.of("col-end-13", "grid-column-end: 13;"),
                SimpleCss.of("col-end-auto", "grid-column-end: auto;"),

                SimpleCss.of("grid-rows-1", "grid-template-rows: repeat(1, minmax(0, 1fr));"),
                SimpleCss.of("grid-rows-2", "grid-template-rows: repeat(2, minmax(0, 1fr));"),
                SimpleCss.of("grid-rows-3", "grid-template-rows: repeat(3, minmax(0, 1fr));"),
                SimpleCss.of("grid-rows-4", "grid-template-rows: repeat(4, minmax(0, 1fr));"),
                SimpleCss.of("grid-rows-5", "grid-template-rows: repeat(5, minmax(0, 1fr));"),
                SimpleCss.of("grid-rows-6", "grid-template-rows: repeat(6, minmax(0, 1fr));"),
                SimpleCss.of("grid-rows-none", "grid-template-rows: none;"),


                SimpleCss.of("row-auto", "grid-row: auto;"),
                SimpleCss.of("row-span-1", "grid-row: span 1 / span 1;"),
                SimpleCss.of("row-span-2", "grid-row: span 2 / span 2;"),
                SimpleCss.of("row-span-3", "grid-row: span 3 / span 3;"),
                SimpleCss.of("row-span-4", "grid-row: span 4 / span 4;"),
                SimpleCss.of("row-span-5", "grid-row: span 5 / span 5;"),
                SimpleCss.of("row-span-6", "grid-row: span 6 / span 6;"),
                SimpleCss.of("row-span-full", "grid-row: 1 / -1;"),
                SimpleCss.of("row-start-1", "grid-row-start: 1;"),
                SimpleCss.of("row-start-2", "grid-row-start: 2;"),
                SimpleCss.of("row-start-3", "grid-row-start: 3;"),
                SimpleCss.of("row-start-4", "grid-row-start: 4;"),
                SimpleCss.of("row-start-5", "grid-row-start: 5;"),
                SimpleCss.of("row-start-6", "grid-row-start: 6;"),
                SimpleCss.of("row-start-7", "grid-row-start: 7;"),
                SimpleCss.of("row-start-auto", "grid-row-start: auto;"),
                SimpleCss.of("row-end-1", "grid-row-end: 1;"),
                SimpleCss.of("row-end-2", "grid-row-end: 2;"),
                SimpleCss.of("row-end-3", "grid-row-end: 3;"),
                SimpleCss.of("row-end-4", "grid-row-end: 4;"),
                SimpleCss.of("row-end-5", "grid-row-end: 5;"),
                SimpleCss.of("row-end-6", "grid-row-end: 6;"),
                SimpleCss.of("row-end-7", "grid-row-end: 7;"),
                SimpleCss.of("row-end-auto", "grid-row-end: auto;"),

                SimpleCss.of("grid-flow-row", "grid-auto-flow: row;"),
                SimpleCss.of("grid-flow-col", "grid-auto-flow: column;"),
                SimpleCss.of("grid-flow-row-dense", "grid-auto-flow: row dense;"),
                SimpleCss.of("grid-flow-col-dense", "grid-auto-flow: column dense;"),


                SimpleCss.of("auto-cols-auto", "grid-auto-columns: auto;"),
                SimpleCss.of("auto-cols-min", "grid-auto-columns: min-content;"),
                SimpleCss.of("auto-cols-max", "grid-auto-columns: max-content;"),
                SimpleCss.of("auto-cols-fr", "grid-auto-columns: minmax(0, 1fr);"),


                SimpleCss.of("auto-rows-auto", "grid-auto-rows: auto;"),
                SimpleCss.of("auto-rows-min", "grid-auto-rows: min-content;"),
                SimpleCss.of("auto-rows-max", "grid-auto-rows: max-content;"),
                SimpleCss.of("auto-rows-fr", "grid-auto-rows: minmax(0, 1fr);"),

                SimpleCss.of("justify-start", "justify-content: flex-start;"),
                SimpleCss.of("justify-end", "justify-content: flex-end;"),
                SimpleCss.of("justify-center", "justify-content: center;"),
                SimpleCss.of("justify-between", "justify-content: space-between;"),
                SimpleCss.of("justify-around", "justify-content: space-around;"),
                SimpleCss.of("justify-evenly", "justify-content: space-evenly;"),

                SimpleCss.of("justify-items-start", "justify-items: start;"),
                SimpleCss.of("justify-items-end", "justify-items: end;"),
                SimpleCss.of("justify-items-center", "justify-items: center;"),
                SimpleCss.of("justify-items-stretch", "justify-items: stretch;"),

                SimpleCss.of("justify-self-auto", "justify-self: auto;"),
                SimpleCss.of("justify-self-start", "justify-self: start;"),
                SimpleCss.of("justify-self-end", "justify-self: end;"),
                SimpleCss.of("justify-self-center", "justify-self: center;"),
                SimpleCss.of("justify-self-stretch", "justify-self: stretch;"),

                SimpleCss.of("content-center", "align-content: center;"),
                SimpleCss.of("content-start", "align-content: flex-start;"),
                SimpleCss.of("content-end", "align-content: flex-end;"),
                SimpleCss.of("content-between", "align-content: space-between;"),
                SimpleCss.of("content-around", "align-content: space-around;"),
                SimpleCss.of("content-evenly", "align-content: space-evenly;"),


                SimpleCss.of("items-start", "align-items: flex-start;"),
                SimpleCss.of("items-end", "align-items: flex-end;"),
                SimpleCss.of("items-center", "align-items: center;"),
                SimpleCss.of("items-baseline", "align-items: baseline;"),
                SimpleCss.of("items-stretch", "align-items: stretch;"),


                SimpleCss.of("self-auto", "align-self: auto;"),
                SimpleCss.of("self-start", "align-self: flex-start;"),
                SimpleCss.of("self-end", "align-self: flex-end;"),
                SimpleCss.of("self-center", "align-self: center;"),
                SimpleCss.of("self-stretch", "align-self: stretch;"),
                SimpleCss.of("self-baseline", "align-self: baseline;"),


                SimpleCss.of("place-content-center", "place-content: center;"),
                SimpleCss.of("place-content-start", "place-content: start;"),
                SimpleCss.of("place-content-end", "place-content: end;"),
                SimpleCss.of("place-content-between", "place-content: space-between;"),
                SimpleCss.of("place-content-around", "place-content: space-around;"),
                SimpleCss.of("place-content-evenly", "place-content: space-evenly;"),
                SimpleCss.of("place-content-stretch", "place-content: stretch;"),


                SimpleCss.of("place-items-start", "place-items: start;"),
                SimpleCss.of("place-items-end", "place-items: end;"),
                SimpleCss.of("place-items-center", "place-items: center;"),
                SimpleCss.of("place-items-stretch", "place-items: stretch;"),

                SimpleCss.of("place-self-auto", "place-self: auto;"),
                SimpleCss.of("place-self-start", "place-self: start;"),
                SimpleCss.of("place-self-end", "place-self: end;"),
                SimpleCss.of("place-self-center", "place-self: center;"),
                SimpleCss.of("place-self-stretch", "place-self: stretch;"),

                SimpleCss.of("w-screen", "width: 100vw;"),
                SimpleCss.of("w-min", "width: min-content;"),
                SimpleCss.of("w-max", "width: max-content;"),
                SimpleCss.of("w-fit", "width: fit-content;"),

                SimpleCss.of("min-w-full", "min-width: 100%;"),
                SimpleCss.of("min-w-min", "min-width: min-content;"),
                SimpleCss.of("min-w-max", "min-width: max-content;"),
                SimpleCss.of("min-w-fit", "min-width: fit-content;"),

                SimpleCss.of("max-w-full", "max-width: 100%;"),
                SimpleCss.of("max-w-min", "max-width: min-content;"),
                SimpleCss.of("max-w-max", "max-width: max-content;"),
                SimpleCss.of("max-w-fit", "max-width: fit-content;"),

                SimpleCss.of("h-screen", "height: 100vh;"),
                SimpleCss.of("h-min", "height: min-content;"),
                SimpleCss.of("h-max", "height: max-content;"),
                SimpleCss.of("h-fit", "height: fit-content;"),

                SimpleCss.of("min-h-screen", "min-height: 100vh;"),
                SimpleCss.of("min-h-min", "min-height: min-content;"),
                SimpleCss.of("min-h-max", "min-height: max-content;"),
                SimpleCss.of("min-h-fit", "min-height: fit-content;"),

                SimpleCss.of("max-h-screen", "max-height: 100vh;"),
                SimpleCss.of("max-h-min", "max-height: min-content;"),
                SimpleCss.of("max-h-max", "max-height: max-content;"),
                SimpleCss.of("max-h-fit", "max-height: fit-content;"),

                SimpleCss.of("font-sans", "font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";"),
                SimpleCss.of("font-serif", "font-family: ui-serif, Georgia, Cambria, \"Times New Roman\", Times, serif;"),
                SimpleCss.of("font-mono", "font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;"),


                SimpleCss.of("text-xs", "font-size: 0.75rem;\n\tline-height: 1rem;"),
                SimpleCss.of("text-sm", "font-size: 0.875rem;\n\tline-height: 1.25rem;"),
                SimpleCss.of("text-base", "font-size: 1rem;\n\tline-height: 1.5rem;"),
                SimpleCss.of("text-lg", "font-size: 1.125rem;\n\tline-height: 1.75rem;"),
                SimpleCss.of("text-xl", "font-size: 1.25rem;\n\tline-height: 1.75rem;"),
                SimpleCss.of("text-2xl", "font-size: 1.5rem;\n\tline-height: 2rem;"),
                SimpleCss.of("text-3xl", "font-size: 1.875rem;\n\tline-height: 2.25rem;"),
                SimpleCss.of("text-4xl", "font-size: 2.25rem;\n\tline-height: 2.5rem;"),
                SimpleCss.of("text-5xl", "font-size: 3rem;\n\tline-height: 1;"),
                SimpleCss.of("text-6xl", "font-size: 3.75rem;\n\tline-height: 1;"),
                SimpleCss.of("text-7xl", "font-size: 4.5rem;\n\tline-height: 1;"),
                SimpleCss.of("text-8xl", "font-size: 6rem;\n\tline-height: 1;"),
                SimpleCss.of("text-9xl", "font-size: 8rem;\n\tline-height: 1;"),

                SimpleCss.of("antialiased", "-webkit-font-smoothing: antialiased;\n\t-moz-osx-font-smoothing: grayscale;"),
                SimpleCss.of("subpixel-antialiased", "-webkit-font-smoothing: auto;\n\t-moz-osx-font-smoothing: auto;"),

                SimpleCss.of("italic", "font-style: italic;"),
                SimpleCss.of("not-italic", "font-style: normal;"),

                SimpleCss.of("font-thin", "font-weight: 100;"),
                SimpleCss.of("font-extralight", "font-weight: 200;"),
                SimpleCss.of("font-light", "font-weight: 300;"),
                SimpleCss.of("font-normal", "font-weight: 400;"),
                SimpleCss.of("font-medium", "font-weight: 500;"),
                SimpleCss.of("font-semibold", "font-weight: 600;"),
                SimpleCss.of("font-bold", "font-weight: 700;"),
                SimpleCss.of("font-extrabold", "font-weight: 800;"),
                SimpleCss.of("font-black", "font-weight: 900;"),

                SimpleCss.of("normal-nums", "font-variant-numeric: normal;"),
                SimpleCss.of("ordinal", "font-variant-numeric: ordinal;"),
                SimpleCss.of("slashed-zero", "font-variant-numeric: slashed-zero;"),
                SimpleCss.of("lining-nums", "font-variant-numeric: lining-nums;"),
                SimpleCss.of("oldstyle-nums", "font-variant-numeric: oldstyle-nums;"),
                SimpleCss.of("proportional-nums", "font-variant-numeric: proportional-nums;"),
                SimpleCss.of("tabular-nums", "font-variant-numeric: tabular-nums;"),
                SimpleCss.of("diagonal-fractions", "font-variant-numeric: diagonal-fractions;"),
                SimpleCss.of("stacked-fractions", "font-variant-numeric: stacked-fractions;"),

                SimpleCss.of("tracking-tighter", "letter-spacing: -0.05em;"),
                SimpleCss.of("tracking-tight", "letter-spacing: -0.025em;"),
                SimpleCss.of("tracking-normal", "letter-spacing: 0em;"),
                SimpleCss.of("tracking-wide", "letter-spacing: 0.025em;"),
                SimpleCss.of("tracking-wider", "letter-spacing: 0.05em;"),
                SimpleCss.of("tracking-widest", "letter-spacing: 0.1em;"),

                SimpleCss.of("leading-3", "line-height: .75rem;"),
                SimpleCss.of("leading-4", "line-height: 1rem;"),
                SimpleCss.of("leading-5", "line-height: 1.25rem;"),
                SimpleCss.of("leading-6", "line-height: 1.5rem;"),
                SimpleCss.of("leading-7", "line-height: 1.75rem;"),
                SimpleCss.of("leading-8", "line-height: 2rem;"),
                SimpleCss.of("leading-9", "line-height: 2.25rem;"),
                SimpleCss.of("leading-10", "line-height: 2.5rem;"),
                SimpleCss.of("leading-none", "line-height: 1;"),
                SimpleCss.of("leading-tight", "line-height: 1.25;"),
                SimpleCss.of("leading-snug", "line-height: 1.375;"),
                SimpleCss.of("leading-normal", "line-height: 1.5;"),
                SimpleCss.of("leading-relaxed", "line-height: 1.625;"),
                SimpleCss.of("leading-loose", "line-height: 2;"),

                SimpleCss.of("list-none", "list-style-type: none;"),
                SimpleCss.of("list-disc", "list-style-type: disc;"),
                SimpleCss.of("list-decimal", "list-style-type: decimal;"),

                SimpleCss.of("list-inside", "list-style-position: inside;"),
                SimpleCss.of("list-outside", "list-style-position: outside;"),

                SimpleCss.of("text-left", "text-align: left;"),
                SimpleCss.of("text-center", "text-align: center;"),
                SimpleCss.of("text-right", "text-align: right;"),
                SimpleCss.of("text-justify", "text-align: justify;"),

                SimpleCss.of("text-inherit", "color: inherit;"),
                SimpleCss.of("text-current", "color: currentColor;"),
                SimpleCss.of("text-transparent", "color: transparent;"),

                SimpleCss.of("underline", "text-decoration-line: underline;"),
                SimpleCss.of("overline", "text-decoration-line: overline;"),
                SimpleCss.of("line-through", "text-decoration-line: line-through;"),
                SimpleCss.of("no-underline", "text-decoration-line: none;"),

                SimpleCss.of("decoration-inherit", "text-decoration-color: inherit;"),
                SimpleCss.of("decoration-current", "text-decoration-color: currentColor;"),
                SimpleCss.of("decoration-transparent", "text-decoration-color: transparent;"),

                SimpleCss.of("decoration-solid", "text-decoration-style: solid;"),
                SimpleCss.of("decoration-double", "text-decoration-style: double;"),
                SimpleCss.of("decoration-dotted", "text-decoration-style: dotted;"),
                SimpleCss.of("decoration-dashed", "text-decoration-style: dashed;"),
                SimpleCss.of("decoration-wavy", "text-decoration-style: wavy;"),

                SimpleCss.of("decoration-auto", "text-decoration-thickness: auto;"),
                SimpleCss.of("decoration-from-font", "text-decoration-thickness: from-font;"),
                SimpleCss.of("decoration-0", "text-decoration-thickness: 0px;"),
                SimpleCss.of("decoration-1", "text-decoration-thickness: 1px;"),
                SimpleCss.of("decoration-2", "text-decoration-thickness: 2px;"),
                SimpleCss.of("decoration-4", "text-decoration-thickness: 4px;"),
                SimpleCss.of("decoration-8", "text-decoration-thickness: 8px;"),

                SimpleCss.of("decoration-auto", "text-decoration-thickness: auto;"),
                SimpleCss.of("decoration-from-font", "text-decoration-thickness: from-font;"),
                SimpleCss.of("decoration-0", "text-decoration-thickness: 0px;"),
                SimpleCss.of("decoration-1", "text-decoration-thickness: 1px;"),
                SimpleCss.of("decoration-2", "text-decoration-thickness: 2px;"),
                SimpleCss.of("decoration-4", "text-decoration-thickness: 4px;"),
                SimpleCss.of("decoration-8", "text-decoration-thickness: 8px;"),

                SimpleCss.of("underline-offset-auto", "text-underline-offset: auto;"),
                SimpleCss.of("underline-offset-0", "text-underline-offset: 0px;"),
                SimpleCss.of("underline-offset-1", "text-underline-offset: 1px;"),
                SimpleCss.of("underline-offset-2", "text-underline-offset: 2px;"),
                SimpleCss.of("underline-offset-4", "text-underline-offset: 4px;"),
                SimpleCss.of("underline-offset-8", "text-underline-offset: 8px;"),

                SimpleCss.of("uppercase", "text-transform: uppercase;"),
                SimpleCss.of("lowercase", "text-transform: lowercase;"),
                SimpleCss.of("capitalize", "text-transform: capitalize;"),
                SimpleCss.of("normal-case", "text-transform: none;"),

                SimpleCss.of("truncate", "overflow: hidden;\n\ttext-overflow: ellipsis;\n\twhite-space: nowrap;"),
                SimpleCss.of("text-ellipsis", "text-overflow: ellipsis;"),
                SimpleCss.of("text-clip", "text-overflow: clip;"),

                SimpleCss.of("align-baseline", "vertical-align: baseline;"),
                SimpleCss.of("align-top", "vertical-align: top;"),
                SimpleCss.of("align-middle", "vertical-align: middle;"),
                SimpleCss.of("align-bottom", "vertical-align: bottom;"),
                SimpleCss.of("align-text-top", "vertical-align: text-top;"),
                SimpleCss.of("align-text-bottom", "vertical-align: text-bottom;"),
                SimpleCss.of("align-sub", "vertical-align: sub;"),
                SimpleCss.of("align-super", "vertical-align: super;"),

                SimpleCss.of("whitespace-normal", "white-space: normal;"),
                SimpleCss.of("whitespace-nowrap", "white-space: nowrap;"),
                SimpleCss.of("whitespace-pre", "white-space: pre;"),
                SimpleCss.of("whitespace-pre-line", "white-space: pre-line;"),
                SimpleCss.of("whitespace-pre-wrap", "white-space: pre-wrap;"),

                SimpleCss.of("break-normal", "overflow-wrap: normal;\n\tword-break: normal;"),
                SimpleCss.of("break-words", "overflow-wrap: break-word;"),
                SimpleCss.of("break-all", "word-break: break-all;"),

                SimpleCss.of("content-none", "content: none;"),

                SimpleCss.of("bg-fixed", "background-attachment: fixed;"),
                SimpleCss.of("bg-local", "background-attachment: local;"),
                SimpleCss.of("bg-scroll", "background-attachment: scroll;"),


                SimpleCss.of("bg-clip-border", "background-clip: border-box;"),
                SimpleCss.of("bg-clip-padding", "background-clip: padding-box;"),
                SimpleCss.of("bg-clip-content", "background-clip: content-box;"),
                SimpleCss.of("bg-clip-text", "background-clip: text;"),

                SimpleCss.of("bg-inherit", "background-color: inherit;"),
                SimpleCss.of("bg-current", "background-color: currentColor;"),
                SimpleCss.of("bg-transparent", "background-color: transparent;"),

                SimpleCss.of("bg-origin-border", "background-origin: border-box;"),
                SimpleCss.of("bg-origin-padding", "background-origin: padding-box;"),
                SimpleCss.of("bg-origin-content", "background-origin: content-box;"),

                SimpleCss.of("bg-bottom", "background-position: bottom;"),
                SimpleCss.of("bg-center", "background-position: center;"),
                SimpleCss.of("bg-left", "background-position: left;"),
                SimpleCss.of("bg-left-bottom", "background-position: left bottom;"),
                SimpleCss.of("bg-left-top", "background-position: left top;"),
                SimpleCss.of("bg-right", "background-position: right;"),
                SimpleCss.of("bg-right-bottom", "background-position: right bottom;"),
                SimpleCss.of("bg-right-top", "background-position: right top;"),
                SimpleCss.of("bg-top", "background-position: top;"),

                SimpleCss.of("bg-repeat", "background-repeat: repeat;"),
                SimpleCss.of("bg-no-repeat", "background-repeat: no-repeat;"),
                SimpleCss.of("bg-repeat-x", "background-repeat: repeat-x;"),
                SimpleCss.of("bg-repeat-y", "background-repeat: repeat-y;"),
                SimpleCss.of("bg-repeat-round", "background-repeat: round;"),
                SimpleCss.of("bg-repeat-space", "background-repeat: space;"),

                SimpleCss.of("bg-auto", "background-size: auto;"),
                SimpleCss.of("bg-cover", "background-size: cover;"),
                SimpleCss.of("bg-contain", "background-size: contain;"),

                SimpleCss.of("rounded-none", "border-radius: var(--dui-spc-0);"),
                SimpleCss.of("rounded-sm", "border-radius: var(--dui-spc-0_5);"),
                SimpleCss.of("rounded", "border-radius: var(--dui-spc-1);"),
                SimpleCss.of("rounded-md", "border-radius: var(--dui-spc-1_5);"),
                SimpleCss.of("rounded-lg", "border-radius: var(--dui-spc-2);"),
                SimpleCss.of("rounded-xl", "border-radius: var(--dui-spc-3);"),
                SimpleCss.of("rounded-2xl", "border-radius: var(--dui-spc-4);"),
                SimpleCss.of("rounded-3xl", "border-radius: var(--dui-spc-6);"),
                SimpleCss.of("rounded-full", "border-radius: 9999px;"),
                SimpleCss.of("rounded-t-none", "border-top-left-radius: var(--dui-spc-0);\n\tborder-top-right-radius: var(--dui-spc-0);"),
                SimpleCss.of("rounded-t-sm", "border-top-left-radius: var(--dui-spc-0_5);\n\tborder-top-right-radius: var(--dui-spc-0_5);"),
                SimpleCss.of("rounded-t", "border-top-left-radius: var(--dui-spc-1);\n\tborder-top-right-radius: var(--dui-spc-1);"),
                SimpleCss.of("rounded-t-md", "border-top-left-radius: var(--dui-spc-1_5);\n\tborder-top-right-radius: var(--dui-spc-1_5);"),
                SimpleCss.of("rounded-t-lg", "border-top-left-radius: var(--dui-spc-2);\n\tborder-top-right-radius: var(--dui-spc-2);"),
                SimpleCss.of("rounded-t-xl", "border-top-left-radius: var(--dui-spc-3);\n\tborder-top-right-radius: var(--dui-spc-3);"),
                SimpleCss.of("rounded-t-2xl", "border-top-left-radius: var(--dui-spc-4);\n\tborder-top-right-radius: var(--dui-spc-4);"),
                SimpleCss.of("rounded-t-3xl", "border-top-left-radius: var(--dui-spc-6);\n\tborder-top-right-radius: var(--dui-spc-6);"),
                SimpleCss.of("rounded-t-full", "border-top-left-radius: 9999px;\n\tborder-top-right-radius: 9999px;"),
                SimpleCss.of("rounded-r-none", "border-top-right-radius: var(--dui-spc-0);\n\tborder-bottom-right-radius: var(--dui-spc-0);"),
                SimpleCss.of("rounded-r-sm", "border-top-right-radius: var(--dui-spc-0_5);\n\tborder-bottom-right-radius: var(--dui-spc-0_5);"),
                SimpleCss.of("rounded-r", "border-top-right-radius: var(--dui-spc-1);\n\tborder-bottom-right-radius: var(--dui-spc-1);"),
                SimpleCss.of("rounded-r-md", "border-top-right-radius: var(--dui-spc-1_5);\n\tborder-bottom-right-radius: var(--dui-spc-1_5);"),
                SimpleCss.of("rounded-r-lg", "border-top-right-radius: var(--dui-spc-2);\n\tborder-bottom-right-radius: var(--dui-spc-2);"),
                SimpleCss.of("rounded-r-xl", "border-top-right-radius: var(--dui-spc-3);\n\tborder-bottom-right-radius: var(--dui-spc-3);"),
                SimpleCss.of("rounded-r-2xl", "border-top-right-radius: var(--dui-spc-4);\n\tborder-bottom-right-radius: var(--dui-spc-4);"),
                SimpleCss.of("rounded-r-3xl", "border-top-right-radius: var(--dui-spc-6);\n\tborder-bottom-right-radius: var(--dui-spc-6);"),
                SimpleCss.of("rounded-r-full", "border-top-right-radius: 9999px;\n\tborder-bottom-right-radius: 9999px;"),
                SimpleCss.of("rounded-b-none", "border-bottom-right-radius: var(--dui-spc-0);\n\tborder-bottom-left-radius: var(--dui-spc-0);"),
                SimpleCss.of("rounded-b-sm", "border-bottom-right-radius: var(--dui-spc-0_5);\n\tborder-bottom-left-radius: var(--dui-spc-0_5);"),
                SimpleCss.of("rounded-b", "border-bottom-right-radius: var(--dui-spc-1);\n\tborder-bottom-left-radius: var(--dui-spc-1);"),
                SimpleCss.of("rounded-b-md", "border-bottom-right-radius: var(--dui-spc-1_5);\n\tborder-bottom-left-radius: var(--dui-spc-1_5);"),
                SimpleCss.of("rounded-b-lg", "border-bottom-right-radius: var(--dui-spc-2);\n\tborder-bottom-left-radius: var(--dui-spc-2);"),
                SimpleCss.of("rounded-b-xl", "border-bottom-right-radius: var(--dui-spc-3);\n\tborder-bottom-left-radius: var(--dui-spc-3);"),
                SimpleCss.of("rounded-b-2xl", "border-bottom-right-radius: var(--dui-spc-4);\n\tborder-bottom-left-radius: var(--dui-spc-4);"),
                SimpleCss.of("rounded-b-3xl", "border-bottom-right-radius: var(--dui-spc-6);\n\tborder-bottom-left-radius: var(--dui-spc-6);"),
                SimpleCss.of("rounded-b-full", "border-bottom-right-radius: 9999px;\n\tborder-bottom-left-radius: 9999px;"),
                SimpleCss.of("rounded-l-none", "border-top-left-radius: var(--dui-spc-0);\n\tborder-bottom-left-radius: var(--dui-spc-0);"),
                SimpleCss.of("rounded-l-sm", "border-top-left-radius: var(--dui-spc-0_5);\n\tborder-bottom-left-radius: var(--dui-spc-0_5);"),
                SimpleCss.of("rounded-l", "border-top-left-radius: var(--dui-spc-1);\n\tborder-bottom-left-radius: var(--dui-spc-1);"),
                SimpleCss.of("rounded-l-md", "border-top-left-radius: var(--dui-spc-1_5);\n\tborder-bottom-left-radius: var(--dui-spc-1_5);"),
                SimpleCss.of("rounded-l-lg", "border-top-left-radius: var(--dui-spc-2);\n\tborder-bottom-left-radius: var(--dui-spc-2);"),
                SimpleCss.of("rounded-l-xl", "border-top-left-radius: var(--dui-spc-3);\n\tborder-bottom-left-radius: var(--dui-spc-3);"),
                SimpleCss.of("rounded-l-2xl", "border-top-left-radius: var(--dui-spc-4);\n\t\n\tborder-bottom-left-radius: var(--dui-spc-4);"),
                SimpleCss.of("rounded-l-3xl", "border-top-left-radius: var(--dui-spc-6);\n\tborder-bottom-left-radius: var(--dui-spc-6);"),
                SimpleCss.of("rounded-l-full", "border-top-left-radius: 9999px;\n\tborder-bottom-left-radius: 9999px;"),
                SimpleCss.of("rounded-tl-none", "border-top-left-radius: var(--dui-spc-0);"),
                SimpleCss.of("rounded-tl-sm", "border-top-left-radius: var(--dui-spc-0_5);"),
                SimpleCss.of("rounded-tl", "border-top-left-radius: var(--dui-spc-1);"),
                SimpleCss.of("rounded-tl-md", "border-top-left-radius: var(--dui-spc-1_5);"),
                SimpleCss.of("rounded-tl-lg", "border-top-left-radius: var(--dui-spc-2);"),
                SimpleCss.of("rounded-tl-xl", "border-top-left-radius: var(--dui-spc-3);"),
                SimpleCss.of("rounded-tl-2xl", "border-top-left-radius: var(--dui-spc-4);"),
                SimpleCss.of("rounded-tl-3xl", "border-top-left-radius: var(--dui-spc-6);"),
                SimpleCss.of("rounded-tl-full", "border-top-left-radius: 9999px;"),
                SimpleCss.of("rounded-tr-none", "border-top-right-radius: var(--dui-spc-0);"),
                SimpleCss.of("rounded-tr-sm", "border-top-right-radius: var(--dui-spc-0_5);"),
                SimpleCss.of("rounded-tr", "border-top-right-radius: var(--dui-spc-1);"),
                SimpleCss.of("rounded-tr-md", "border-top-right-radius: var(--dui-spc-1_5);"),
                SimpleCss.of("rounded-tr-lg", "border-top-right-radius: var(--dui-spc-2);"),
                SimpleCss.of("rounded-tr-xl", "border-top-right-radius: var(--dui-spc-3);"),
                SimpleCss.of("rounded-tr-2xl", "border-top-right-radius: var(--dui-spc-4);"),
                SimpleCss.of("rounded-tr-3xl", "border-top-right-radius: var(--dui-spc-6);"),
                SimpleCss.of("rounded-tr-full", "border-top-right-radius: 9999px;"),
                SimpleCss.of("rounded-br-none", "border-bottom-right-radius: var(--dui-spc-0);"),
                SimpleCss.of("rounded-br-sm", "border-bottom-right-radius: var(--dui-spc-0_5);"),
                SimpleCss.of("rounded-br", "border-bottom-right-radius: var(--dui-spc-1);"),
                SimpleCss.of("rounded-br-md", "border-bottom-right-radius: var(--dui-spc-1_5);"),
                SimpleCss.of("rounded-br-lg", "border-bottom-right-radius: var(--dui-spc-2);"),
                SimpleCss.of("rounded-br-xl", "border-bottom-right-radius: var(--dui-spc-3);"),
                SimpleCss.of("rounded-br-2xl", "border-bottom-right-radius: var(--dui-spc-4);"),
                SimpleCss.of("rounded-br-3xl", "border-bottom-right-radius: var(--dui-spc-6);"),
                SimpleCss.of("rounded-br-full", "border-bottom-right-radius: 9999px;"),
                SimpleCss.of("rounded-bl-none", "border-bottom-left-radius: var(--dui-spc-0);"),
                SimpleCss.of("rounded-bl-sm", "border-bottom-left-radius: var(--dui-spc-0_5);"),
                SimpleCss.of("rounded-bl", "border-bottom-left-radius: var(--dui-spc-1);"),
                SimpleCss.of("rounded-bl-md", "border-bottom-left-radius: var(--dui-spc-1_5);"),
                SimpleCss.of("rounded-bl-lg", "border-bottom-left-radius: var(--dui-spc-2);"),
                SimpleCss.of("rounded-bl-xl", "border-bottom-left-radius: var(--dui-spc-3);"),
                SimpleCss.of("rounded-bl-2xl", "border-bottom-left-radius: var(--dui-spc-4);"),
                SimpleCss.of("rounded-bl-3xl", "border-bottom-left-radius: var(--dui-spc-6);"),
                SimpleCss.of("rounded-bl-full", "border-bottom-left-radius: 9999px;"),


                SimpleCss.of("", ""),


                );


        Configuration configuration = new Configuration(Configuration.VERSION_2_3_29);
        configuration.setClassForTemplateLoading(SpacingGenerator.class, "/");
        configuration.setDefaultEncoding("UTF-8");
        configuration.setTemplateExceptionHandler(TemplateExceptionHandler.RETHROW_HANDLER);
        configuration.setLogTemplateExceptions(false);
        configuration.setWrapUncheckedExceptions(true);
        configuration.setFallbackOnNullLoopVariable(false);

        Template spacingTemplate = configuration.getTemplate("SpacingTemplate.ftl");
        Map<String, Object> spacignParams = new HashMap<>();
        spacignParams.put("spacings", spacings);


        Path source = Paths.get(SpacingGenerator.class.getResource("/").getPath());

        File file = Paths.get(source.toAbsolutePath().toString(), "spacing.css").toFile();
        FileWriter fileWriter = new FileWriter(file);

        spacingTemplate.process(spacignParams, fileWriter);

        Template simpleTemplate = configuration.getTemplate("SimpleCssTemplate.ftl");

        Map<String, Object> simpleParams = new HashMap<>();
        simpleParams.put("displayStyles", displayStyles);

        simpleTemplate.process(simpleParams, fileWriter);

    }

}
