#
# Copyright © 2019 Dominokit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Deploy

on:
  push:
    branches: [ master, development ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Run Maven verify
        run: ./mvnw verify -B -e

  release:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Java for deployment
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Import GPG key
        run: |
          echo "${{ secrets.gpg_private_key }}" | gpg --batch --import
        env:
          GPG_TTY: $(tty)
      - name: Deploy with Maven
        run: ./mvnw --no-transfer-progress clean deploy -B -e -Dgpg.passphrase=${{ secrets.gpg_passphrase }}
        env:
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}

